### ISSUE TITLE
Issue removing glycan

### ISSUE THREAD

**Issue by meteosR** [ibmm-unibe-ch/glycosylator#3] opened 2024-08-03 06:06 UTC
Hello ! I have been trying to remove glycans but often find issues. Not sure if I am doing something wrong. 

Here is the code I have been using, where `path_in` is cif file 1A7S (added as txt due to github restrictions).
[1A7S.txt](https://github.com/user-attachments/files/16478270/1A7S.txt)

```
ref_residues_glycans = resources.reference_glycan_residue_ids()

scaffold = gl.protein(path_in)
scaffold.reindex()
scaffold.infer_bonds()

all_glycan_residues = set([r for r in scaffold.get_residues() if r.resname in ref_residues_glycans])
print("\nall_glycan_residues", all_glycan_residues)

# Find glycans
print("\nLooking for glycans")
glycans = scaffold.find_glycans()

# Remove all glycans
print("\nPreparing to remove glycans")
for k, g in glycans.items():
    print("Removing glycan", g)
    scaffold.remove_glycan(g)

all_glycan_residues = set([r for r in scaffold.get_residues() if r.resname in ref_residues_glycans])
print("\nall_glycan_residues after removal", all_glycan_residues)
```
Here is the output. Residue NAG 563 does not seem to be removed.
<img width="512" alt="image" src="https://github.com/user-attachments/assets/2f5ec7fd-0e96-43af-b67f-5dd03473e2b4">

Attempting to remove it directly with .remove_residues() results in an error as well. 
<img width="429" alt="image" src="https://github.com/user-attachments/assets/5436c897-aca0-4373-bb33-388aeebcdd09">

Thank you for any help and for all the work to build glycosylator !

**Comment by NoahHenrikKleinschmidt** [comment] 2024-08-05 14:41
Heyhow, 
I see, that was an interesting one! So to boil it down, the issue was that when using `find_glycans()` there was a double-reference to that residue (once from the glycan and once from the scaffold), even though they are supposed to share the same reference. Therefore, when using `remove_glycan` the references are deleted under the assumption that they are shared, which was not the case due to a bug in `find_glycans`, and thus leaving one reference intact, even though the object was already gone - that's the error you were seeing when trying to delete manually. 

This should now be fixed. If you like, you can directly clone the repository and install from the `dev` branch, or get the fix in the next release 😄. 


Here's the code that works for me:
```python
import glycosylator as gl

# load the protein
protein_file = "~/Downloads/1A7S.cif"
protein = gl.Protein.from_cif(protein_file)

# no need to infer all bonds!
# if you did it because the Hydrogenator step was complaining, you can simply use:
# protein.apply_standard_bonds_for([i.parent for i in protein.get_glycans().keys()])
# but even that is not needed in the new version. If no bonds are available, simply no hydrogens are added...

# now remove the glycans
for g in protein.glycans:
    protein.remove_glycan(g)

# now export to a file
protein.to_pdb("~/Downloads/1A7S_no_glycans.pdb")
```

Which now looks like this (I colored in the waters in blue, the chlorine in green, and the ethanol's in gray, protein is orange, of course ^^):

https://github.com/user-attachments/assets/64367f9c-55d7-4b48-9888-c9154d98f5cc

> Here is the PDB output if you are interested. 
> - [1A7S_no_glycans.pdb.txt](https://github.com/user-attachments/files/16499116/1A7S_no_glycans.pdb.txt) has everything in chain A.
> - [1A7S_no_glycans_sorted.pdb.txt](https://github.com/user-attachments/files/16499074/1A7S_no_glycans_sorted.pdb.txt) has the waters separated into a chain W and the ethanol and the chlorine into a chain L, protein is chain A.

**Comment by meteosR** [comment] 2024-08-05 21:01
Thank you for the fix ! Three follow-ups:

1. I don't know if this is the expected behavior but removing the glycans still keeps the bonds between atoms within the monosaccharides (when calling `protein.get_bonds()`). 

2. I used `scaffold.infer_bonds()` since not using it resulted in the following error when attaching the glycans
<img width="874" alt="image" src="https://github.com/user-attachments/assets/19958391-bd65-430e-99d5-e63f93d93edd">



3. And following the initial code above, after deleting the original glycans in 1A7S I am trying to attach brand new glycans at certain positions. 

```
protein_alphabet = ['ALA', 'ARG', 'ASN', 'ASP', 'CYS', 'GLN', 'GLU', 'GLY', 'HSD', 'HIS', 'HIE', 'HID', 'HSE',
                    'HSP', 'ILE', 'LEU', 'LYS', 'MET', 'PHE', 'PRO', 'SER', 'THR', 'TRP', 'TYR', 'VAL']

iupac = "Man(a1-3)[Man(a1-6)]Man(a1-6)[Man(a1-3)]Man(b1-4)GlcNAc(b1-4)GlcNAc" # MAN5

# Remove all glycans, store atoms where they were attached
previously_n_linked_atoms = []
for k, g in glycans.items():
    if k.get_parent().resname.lower() in ["asn", "nln"]:
        previously_n_linked_atoms.append(k)
    scaffold.remove_glycan(g)
print("\nlinked_atoms_n_linked", previously_n_linked_atoms)

all_glycan_residues = set([r for r in scaffold.get_residues() if r.resname in ref_residues_glycans])
print("\nall_glycan_residues after removal", all_glycan_residues)

# Remove non-protein
for residue in scaffold.get_residues():
    if residue.resname not in protein_alphabet:
        scaffold.remove_residues(residue)

# Rename hydrogen atoms, Hydrogenator seems to modify name
scaffold.rename_atoms("HND22", "HD22").rename_atoms("HND21", "HD21")

# Add new glycans at specific sites 
for anchor_atom in previously_n_linked_atoms:
    glycan = gl.glycan(iupac)
    glycan.root_atom = glycan.get_atom("C1", residue=1)
    res = anchor_atom.get_parent()
    link = gl.linkage("ND2", "C1", ["HD22"], ["O1", "HO1"])
    scaffold.root_atom = scaffold.get_atom("ND2", residue=res)
    scaffold.attach(mol=glycan, link=link, residues=[res])

scaffold.to_pdb("debug_3_gly_added.pdb")
```
For ASN110 there is no issue:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/77fbad3c-d939-4832-bf73-60de25e462f0">

However, the resulting structure seems to have some issues with the attached glycan at position ASN141 (I am not concerned about clashes, just that the bonds seem to be messed up)
<img width="701" alt="image" src="https://github.com/user-attachments/assets/1a1b518a-f725-472d-a431-401287f36e73">

[debug_3_gly_added.txt](https://github.com/user-attachments/files/16502856/debug_3_gly_added.txt)

**Comment by NoahHenrikKleinschmidt** [comment] 2024-08-06 11:19
Mhmm, I see. Well let's dive into this one then! 

So, if I understand correctly, you are trying to add the Man5 glycan to the two residues that were previously glycosylated with something else and do some structure cleanup along the way. 

So here's how I did it: 

## Step 1 Load and Clean
Get the protein and remove waters and other unwanted things

```python
protein_file = "~/Downloads/1A7S.cif"
protein = gl.Protein.from_cif(protein_file)
protein.reindex()

# Remove waters and Ethanol and Chloride
protein.remove_residues(*(
    protein.get_residues("HOH") + 
    protein.get_residues("CL") + 
    protein.get_residues("EOH"))
   )
```

## Step 2 Remove Glycans
Clear the existing glycans from the glycosylation sites

```python
# find glycans (assign them to a new chain, optional)
protein.find_glycans(chain="new")

# now remove them
glyco_sites = []
for anchor, g in list(protein.get_glycans().items()):
    protein.remove_glycan(g)
    glyco_sites.append(anchor.parent)
```

## Step 3 Processing
Now add bond data so Glycosylator can add new glycans again

```python
# add connectivity information
# (is more efficient than simply calling protein.infer_bonds())
protein.apply_standard_bonds()
protein.infer_residue_connections(triplet=False)

# add hydrogens 
protein.add_hydrogens()
# more efficient would be:
# protein.add_hydrogens([res.get_atom("ND2") for res in glyco_sites])

# and rename the hydrogens accordingly
protein.rename_atoms("HND22", "HD22").rename_atoms("HND21", "HD21")
```

> Checkpoint: `protein.to_pdb("~/Downloads/1A7S_no_glycans_cleaned.pdb")`


## Step 4 Glycosylate
Make the glycan(s?) to add onto the protein and glycosylate the previously cleared sites

```python
# make the glycan
iupac = "Man(a1-3)[Man(a1-6)]Man(a1-6)[Man(a1-3)]Man(b1-4)GlcNAc(b1-4)GlcNAc" # MAN5
glycan = gl.glycan(iupac)

# and glycosylate the protein
# (no need to define the linkage since if all residues are ASN, otherwise keep your linkage definition and pass as argument)
protein.attach(glycan, residues=glyco_sites)
```

> Checkpoint: `protein.to_pdb("~/Downloads/1A7S_man5.pdb")`


## Step 5 (optional) Improve conformation
If we don't like the conformation we can try improving it with some optimization. 
The code cell ran for roughly 20 seconds on my laptop and it took me some 10 trials to get something I found okey.

```python
protein_opt = protein.copy()

# experiment a bit with parameters
graph, edges = gl.make_scaffold_graph(protein_opt, False, slice=3, include_root=True, include_n_ancestors=1)

# here too
env = gl.DistanceRotatron(graph, edges, unfold=2.5)
env = gl.ScaffoldRotatron(env)

# run optimization
protein_opt = gl.optimize(protein_opt, env)
```
> Checkpoint: `protein_opt.to_pdb("~/Downloads/1A7S_man5_opt.pdb")`

https://github.com/user-attachments/assets/63631066-d82b-4985-bc8e-96b93e2eb15f

> Here's my PDB files
> - [1A7S_man5.pdb.txt](https://github.com/user-attachments/files/16509455/1A7S_man5.pdb.txt)
> - [1A7S_man5_opt.pdb.txt](https://github.com/user-attachments/files/16509456/1A7S_man5_opt.pdb.txt)

**Comment by NoahHenrikKleinschmidt** [comment] 2024-08-06 11:23
Regarding the bonds that were still remaining: Yep, I forgot about those. That should be fixed now as well on the `dev` branch! 

Regarding the strangely stretched bonds, I did not observe that kind of behavior when running the (the one I wrote, I haven't tried your's) code, so I'm not really sure what happened there, to be honest 😅 . Try out the code I provided and if you keep observing the bond distortions we should open a new issue for that one 🤔 

<details>
<summary>My thoughts on the matter</summary>

Depending on the versions you have installed, it could be related to an issue that BuildAMol had when getting multiple identical molecules through repeatedly calling `get_compound(...)` rather than calling the function once and then using `mol.copy()` to get new copies. In your glycosylation loop you call `glycan(iupac)` multiple times which will forward stuff to `get_compound`, so it could be caused by that. 

You could try to do something like this (below) to check if the issue persists:

```python
# make the glycan once
glycan = gl.glycan(iupac)

for atom in atoms_to_glycosylate:
     res = atom.parent
     incoming = glycan.copy() # then use copies
     protein.attach(incoming, residues=[res])
```

</details>

**Comment by meteosR** [comment] 2024-08-08 21:07
The repeated calling of gl.glycan(iupac) seemed to be the issue, making the copy solved it. Thank you so much!

**Comment by NoahHenrikKleinschmidt** [comment] 2024-08-09 09:30
Perfect! I'm glad to hear that it works now 😄 . 

Using copies is also faster than re-building the glycan multiple times. But if you update to the newest BuildAMol version, the issue with multiple `glycan(...)` calls should disappear, so your code should work even now! 

I guess, we can mark this issue as solved then?

**Closed as completed** 2024-08-12 05:39 UTC
